from __future__ import annotations

from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUTPUT = DOCS / "_data" / "docs_index.yml"
INDEXED_SUFFIXES = {".md", ".pdf"}
SKIP_PARTS = {
    ".jekyll-cache",
    "_data",
    "_includes",
    "_layouts",
    "_site",
    "docs",
    "dop-archiecture",  # typo duplicate of dop-architecture; pending git rm
    "internal",
    "node_modules",
}


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def title_for(path: Path) -> str:
    if path.name.lower() == "readme.md":
        return path.parent.name.replace("-", " ").replace("_", " ").title()

    title = path.stem.replace("-", " ").replace("_", " ").strip()
    title = title.replace("–", "-")
    return " ".join(title.split()).title()


def site_url_for(relative: Path) -> str:
    if relative.suffix.lower() == ".md":
        if relative.name.lower() == "readme.md":
            parent = relative.parent.as_posix()
            return "/" if parent == "." else "/" + quote(parent, safe="/") + "/"
        return "/" + quote(relative.with_suffix("").as_posix(), safe="/") + "/"
    return "/" + quote(relative.as_posix(), safe="/")


def should_index(path: Path) -> bool:
    relative = path.relative_to(DOCS)
    if path.suffix.lower() not in INDEXED_SUFFIXES:
        return False
    if any(part in SKIP_PARTS for part in relative.parts):
        return False
    return path.name.lower() not in {"license"}


def main() -> None:
    entries = []
    for path in sorted(DOCS.rglob("*")):
        if not path.is_file() or not should_index(path):
            continue

        relative = path.relative_to(DOCS).as_posix()
        relative_path = path.relative_to(DOCS)
        entries.append(
            {
                "title": title_for(path),
                "path": relative,
                "url": site_url_for(relative_path),
                "format": path.suffix.lower().lstrip("."),
            }
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools/generate_docs_index.py",
        "# Do not edit by hand.",
    ]
    for entry in entries:
        lines.extend(
            [
                f"- title: {yaml_quote(entry['title'])}",
                f"  path: {yaml_quote(entry['path'])}",
                f"  url: {yaml_quote(entry['url'])}",
                f"  format: {yaml_quote(entry['format'])}",
            ]
        )
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(entries)} entries to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
